// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs():Promise<void>;

export function GetLogs():Promise<string>;

export function IsRunning():Promise<boolean>;

export function StartProxy(arg1:string,arg2:number):Promise<void>;

export function StopProxy():Promise<void>;
