// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function GetEndpoints() {
  return window['go']['app']['App']['GetEndpoints']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function IsRunning() {
  return window['go']['app']['App']['IsRunning']();
}

export function StartProxy() {
  return window['go']['app']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['app']['App']['StopProxy']();
}
