// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ClearLogs():Promise<void>;

export function GetEndpoints():Promise<app.EndpointsResponse>;

export function GetLogs():Promise<string>;

export function IsRunning():Promise<boolean>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;
