import React, { useEffect, useRef, useState } from "react";
import { Sparkles } from "lucide-react";

// Wails runtime event helpers (already generated by template)
import { EventsOn, EventsOff } from "../wailsjs/runtime/runtime.js";

// Prefer the generated bindings if they exist, otherwise fall back to window.go
// The generated file will update after running `wails dev`/`wails build`
let API = null;
try {
  // eslint-disable-next-line no-undef
  API = window?.go?.app?.App;
} catch (_) {
  API = null;
}

function Badge({ children, variant = "success" }) {
  const dot =
    variant === "success"
      ? "bg-emerald-400"
      : variant === "danger"
      ? "bg-rose-400"
      : "bg-slate-400";

  return (
    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ring-1 ring-inset bg-neutral-900 text-slate-300 ring-neutral-800">
      <span className={`h-1.5 w-1.5 rounded-full ${dot}`} />
      {children}
    </span>
  );
}

const describeEndpoint = (p) => {
  if (!p) return "Proxied endpoint.";
  if (p.includes("/openai/") && p.includes("chat/completions")) return "OpenAI Chat Completions-compatible endpoint.";
  if (p.includes("/bedrock/claude/") && p.includes("/messages")) return "Anthropic Claude Messages on AWS Bedrock.";
  if (p.includes("/provider/bedrock/format/openai") && p.includes("chat/completions")) return "Translates OpenAI Chat Completions format to Bedrock/Anthropic.";
  return "Proxied endpoint.";
};

export default function App() {
  const [port, setPort] = useState(null);
  const [running, setRunning] = useState(false);
  const [logs, setLogs] = useState("");
  const [busy, setBusy] = useState(false);
  const [endpoints, setEndpoints] = useState([]);

  // Dark theme only
  const logsRef = useRef(null);

  // Auto-scroll logs
  useEffect(() => {
    if (!logsRef.current) return;
    logsRef.current.scrollTop = logsRef.current.scrollHeight;
  }, [logs]);

  // Initialisation: fetch defaults & status
  useEffect(() => {
    let mounted = true;

    (async () => {
      try {
        if (API?.IsRunning) {
          const s = await API.IsRunning();
          if (mounted) setRunning(!!s);
        }
        if (API?.GetLogs) {
          const l = await API.GetLogs();
          if (mounted && l) setLogs(l);
        }
        if (API?.GetEndpoints) {
          const info = await API.GetEndpoints();
          if (mounted && info) {
            if (info.endpoints) setEndpoints(info.endpoints);
          }
        }
        if (API?.GetPort) {
          const p = await API.GetPort();
          if (mounted) setPort(p);
        }
      } catch (e) {
        // ignore
      }
    })();

    // Subscribe to runtime events
    const offA = EventsOn("proxy:status", (status) => {
      setRunning(status === "running");
    });
    const offB = EventsOn("proxy:log", (line) => {
      setLogs((prev) => prev + (prev.endsWith("\n") || prev.length === 0 ? "" : "\n") + line);
    });
    const offC = EventsOn("proxy:log:cleared", () => setLogs(""));

    return () => {
      mounted = false;
      try {
        EventsOff("proxy:status", offA);
        EventsOff("proxy:log", offB);
        EventsOff("proxy:log:cleared", offC);
      } catch (_) {
        // ignore
      }
    };
  }, []);


  const onStart = async () => {
    if (!API?.StartProxy) return;
    setBusy(true);
    try {
      await API.StartProxy();
    } catch (e) {
      console.error(e);
    } finally {
      setBusy(false);
    }
  };

  const onStop = async () => {
    if (!API?.StopProxy) return;
    setBusy(true);
    try {
      await API.StopProxy();
    } catch (e) {
      console.error(e);
    } finally {
      setBusy(false);
    }
  };

  const onClearLogs = async () => {
    if (!API?.ClearLogs) {
      setLogs("");
      return;
    }
    await API.ClearLogs();
  };

  const refreshEndpoints = async () => {
    if (!API?.GetEndpoints) return;
    try {
      const info = await API.GetEndpoints();
      setEndpoints(info?.endpoints || []);
    } catch (e) {}
  };


  return (
    <div className="h-screen overflow-hidden select-none bg-slate-900 text-slate-100 relative flex flex-col">
      <div className="fixed top-0 left-0 right-0 h-2 app-drag z-10" />
      <header className="px-3 py-3 border-b border-neutral-700 bg-neutral-900/60 backdrop-blur">
        <div className="w-full flex items-center justify-between app-no-drag">
          <div className="flex items-center gap-3">
            <div className="h-9 w-9 rounded-lg bg-neutral-800/60 ring-1 ring-neutral-700 grid place-items-center">
              <Sparkles className="h-5 w-5 text-slate-300" />
            </div>
            <div>
              <h1 className="text-lg font-semibold tracking-tight text-slate-200">
                Proximity
              </h1>
              <p className="text-xs text-slate-400">
                Enterprise AI APIs via AI-Gateway.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {port != null && (
              <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ring-1 ring-inset bg-neutral-900 text-slate-300 ring-neutral-800 select-text cursor-text">{`listening on port ${port}`}</span>
            )}
            {!running ? (
              <button
                disabled={busy}
                onClick={onStart}
                className="inline-flex items-center justify-center w-28 rounded-md bg-[#0a84ff] hover:bg-[#409cff] text-white font-medium px-3 py-1.5 text-sm disabled:opacity-50 disabled:cursor-not-allowed transition"
              >
                Start Proxy
              </button>
            ) : (
              <button
                disabled={busy}
                onClick={onStop}
                className="inline-flex items-center justify-center w-28 rounded-md bg-[#ff453a] hover:bg-[#ff6961] text-white font-medium px-3 py-1.5 text-sm disabled:opacity-50 disabled:cursor-not-allowed transition"
              >
                Stop Proxy
              </button>
            )}
          </div>
        </div>
      </header>

      <main className="p-3 flex-1 overflow-hidden min-h-0 min-w-0">
        <div className="w-full grid h-full min-h-0 min-w-0 overflow-hidden gap-3 md:grid-cols-[280px_minmax(0,1fr)] max-w-6xl mx-auto">
          {/* Control Panel */}
          <section>
            <div className="h-full min-h-0 flex flex-col rounded-lg border border-neutral-700 bg-neutral-800/60 p-4">
              <h2 className="text-sm font-medium text-slate-200 mb-4">Configuration</h2>

              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-medium text-slate-400">Exposed endpoints</h3>
                  <button
                    onClick={refreshEndpoints}
                    className="text-xs text-slate-400 hover:text-slate-200"
                  >
                    Refresh
                  </button>
                </div>
                <div className="rounded-md border border-neutral-700 bg-neutral-800 overflow-hidden">
                  <div className="max-h-48 overflow-auto divide-y divide-neutral-700">
                    {endpoints?.length ? (
                      endpoints.map((e, i) => (
                        <div key={i} className="px-3 py-2">
                          <div className="flex items-center gap-2">
                            <code className="font-mono text-[11px] text-slate-300 bg-neutral-900/70 border border-neutral-700 rounded px-2 py-1">
                              {e.in}
                            </code>
                          </div>
                          <div className="text-[11px] text-slate-400 mt-1">
                            {describeEndpoint(e.in)}
                          </div>
                        </div>
                      ))
                    ) : (
                      <div className="px-3 py-4 text-xs text-slate-500">No endpoints configured.</div>
                    )}
                  </div>
                </div>
              </div>

              <div className="mt-auto pt-4"></div>

            </div>
          </section>

          {/* Logs */}
          <section className="md:col-start-2 min-h-0 min-w-0 h-full overflow-hidden">
            <div className="rounded-lg border border-neutral-700 bg-neutral-800/60 p-0 divide-y divide-neutral-700 h-full min-h-0 min-w-0 w-full flex flex-col overflow-hidden">
              <div className="flex items-center justify-between px-3 py-3 bg-neutral-800 shrink-0">
                <div className="text-sm font-semibold text-slate-300">Logs</div>
                <button
                  onClick={onClearLogs}
                  className="inline-flex items-center rounded-md border border-neutral-700 bg-neutral-800 hover:bg-neutral-700 px-3 py-1.5 text-sm text-slate-200 transition"
                >
                  Clear logs
                </button>
              </div>
              <div
                ref={logsRef}
                className="font-mono text-xs leading-relaxed text-slate-200/90 whitespace-pre-wrap break-all bg-neutral-900 p-3 overflow-auto flex-1 w-full min-w-0 min-h-0 max-h-full select-text"
              >
                {logs?.length ? logs : "No logs yet."}
              </div>
            </div>
          </section>
        </div>
      </main>

    </div>
  );
}
