import React, { useEffect, useRef, useState } from "react";
import { Sparkles } from "lucide-react";

// Wails runtime event helpers (already generated by template)
import { EventsOn, EventsOff } from "../wailsjs/runtime/runtime.js";

// Import provider logos
import openaiLogo from "./assets/images/openai-gpt.png";
import claudeLogo from "./assets/images/anthropic-claude.png";
import geminiLogo from "./assets/images/google-gemini.png";

// Prefer the generated bindings if they exist, otherwise fall back to window.go
// The generated file will update after running `wails dev`/`wails build`
let API = null;
try {
  // eslint-disable-next-line no-undef
  API = window?.go?.app?.App;
} catch (_) {
  API = null;
}

const describeEndpoint = (p) => {
  if (p == "/openai/v1/chat/completions") {
    return "Chat endpoint";
  }

  if (p == "/openai/v1/responses") {
    return "Response endpoint";
  }

  if (p == "/openai/v1/images/generations") {
    return "Image generation endpoint";
  }

  if (p == "/openai/v1/models") {
    return "Model list endpoint";
  }

  if (p == "/bedrock/claude/v1/messages") {
    return "Chat endpoint";
  }

  if (p == "/bedrock/claude/v1/models") {
    return "Model list endpoint";
  }

  if (p == "/provider/bedrock/format/openai/v1/chat/completions") {
    return "OpenAI compatible chat endpoint";
  }

  if (p == "/provider/bedrock/format/openai/v1/models") {
    return "OpenAI compatible model list endpoint";
  }

  if (p == "/google/gemini/v1beta/models/{model}:generateContent") {
    return "Chat endpoint";
  }

  if (p == "/google/gemini/v1beta/models/{model}:streamGenerateContent") {
    return "Streamed chat endpoint";
  }

  return "Proxied endpoint.";
};


const getEndpointProvider = (path) => {
  if (path.startsWith("/openai")) return "OpenAI";
  if (path.startsWith("/bedrock")) return "Claude";
  if (path.startsWith("/provider/bedrock")) return "Claude";
  if (path.startsWith("/google")) return "Gemini";
  return "Other";
};

const groupEndpoints = (endpoints) => {
  if (!endpoints) return {};
  return endpoints.reduce((acc, endpoint) => {
    const provider = getEndpointProvider(endpoint.in);
    if (!acc[provider]) {
      acc[provider] = [];
    }
    acc[provider].push(endpoint);
    return acc;
  }, {});
};

const getProviderLogo = (provider) => {
  const logos = {
    "OpenAI": openaiLogo,
    "Claude": claudeLogo,
    "Gemini": geminiLogo,
  };
  return logos[provider] || null;
};

export default function App() {
  const [port, setPort] = useState(null);
  const [running, setRunning] = useState(false);
  const [logs, setLogs] = useState("");
  const [endpoints, setEndpoints] = useState([]);
  const [activeTab, setActiveTab] = useState("routes");
  const [showCopiedToast, setShowCopiedToast] = useState(false);

  // Dark theme only
  const logsRef = useRef(null);
  const toastTimeoutRef = useRef(null);

  // Auto-scroll logs
  useEffect(() => {
    if (!logsRef.current || activeTab !== "logs") return;
    logsRef.current.scrollTop = logsRef.current.scrollHeight;
  }, [logs, activeTab]);

  useEffect(() => {
    document.documentElement.classList.add("dark");
  }, []);

  // Initialisation: fetch defaults & status
  useEffect(() => {
    let mounted = true;

    (async () => {
      try {
        if (API?.IsRunning) {
          const s = await API.IsRunning();
          if (mounted) setRunning(!!s);
        }
        if (API?.GetLogs) {
          const l = await API.GetLogs();
          if (mounted && l) setLogs(l);
        }
        if (API?.GetEndpoints) {
          const info = await API.GetEndpoints();
          if (mounted && info) {
            if (info.endpoints) setEndpoints(info.endpoints);
          }
        }
        if (API?.GetPort) {
          const p = await API.GetPort();
          if (mounted) setPort(p);
        }
      } catch (e) {
        // ignore
      }
    })();

    // Subscribe to runtime events
    const offA = EventsOn("proxy:status", (status) => {
      setRunning(status === "running");
    });
    const offB = EventsOn("proxy:log", (line) => {
      setLogs((prev) => prev + (prev.endsWith("\n") || prev.length === 0 ? "" : "\n") + line);
    });
    const offC = EventsOn("proxy:log:cleared", () => setLogs(""));

    return () => {
      mounted = false;
      try {
        EventsOff("proxy:status", offA);
        EventsOff("proxy:log", offB);
        EventsOff("proxy:log:cleared", offC);
      } catch (_) {
        // ignore
      }
    };
  }, []);


  const onStart = async () => {
    if (!API?.StartProxy) return;
    try {
      await API.StartProxy();
    } catch (e) {
      console.error(e);
    }
  };

  const onStop = async () => {
    if (!API?.StopProxy) return;
    try {
      await API.StopProxy();
    } catch (e) {
      console.error(e);
    }
  };

  const onClearLogs = async () => {
    if (!API?.ClearLogs) {
      setLogs("");
      return;
    }
    await API.ClearLogs();
  };

  const copyToClipboard = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      
      // Clear any existing timeout
      if (toastTimeoutRef.current) {
        clearTimeout(toastTimeoutRef.current);
      }
      
      // Show toast
      setShowCopiedToast(true);
      
      // Hide toast after 3 seconds
      toastTimeoutRef.current = setTimeout(() => {
        setShowCopiedToast(false);
      }, 3000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (toastTimeoutRef.current) {
        clearTimeout(toastTimeoutRef.current);
      }
    };
  }, []);



  return (
    <div className="h-screen overflow-hidden select-none bg-transparent text-slate-800 dark:text-slate-100 relative flex flex-col">
      <div className="fixed top-0 left-0 right-0 h-2 app-drag z-10" />
      <header
        style={{ "--wails-draggable": "drag" }}
        className="px-3 pb-2 pt-3 bg-transparent h-20 flex items-end shadow-inner"
      >
        <div className="relative w-full flex items-center justify-between app-no-drag">
          <div
            style={{ "--wails-draggable": "no-drag" }}
            className="absolute left-1/2 -translate-x-1/2 flex items-center gap-2"
          >
            <div className="relative inline-flex rounded-lg bg-black/10 dark:bg-black/20 p-0.5 overflow-hidden shadow-inner shadow-black/10">
              <span
                className={`pointer-events-none absolute top-0.5 left-0.5 bottom-0.5 w-24 rounded-md bg-[#1bc15b] dark:bg-[#1bc15b]/80 backdrop-blur-sm ring-1 ring-black/5 transform-gpu transition-transform duration-150 ease-in-out shadow-md shadow-black/20 border border-white/20 ${
                  activeTab === "logs" ? "translate-x-24" : "translate-x-0"
                }`}
              />
              <button
                onClick={() => setActiveTab("routes")}
                className={`relative z-10 w-24 text-center px-3 py-1.5 text-sm rounded-md transition-colors duration-150 ${
                  activeTab === "routes"
                    ? "text-slate-800 dark:text-slate-100"
                    : "text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200"
                }`}
              >
                Routes
              </button>
              <button
                onClick={() => setActiveTab("logs")}
                className={`relative z-10 w-24 text-center px-3 py-1.5 text-sm rounded-md transition-colors duration-150 ${
                  activeTab === "logs"
                    ? "text-slate-800 dark:text-slate-100"
                    : "text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200"
                }`}
              >
                Logs
              </button>
            </div>
          </div>
          <div
            style={{ "--wails-draggable": "drag" }}
            className="flex items-center gap-2"
          >
            <div className="h-8 w-8 rounded-md bg-[#8A2BE2] grid place-items-center transition border border-white/20 shadow-lg shadow-black/20">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <div>
              <h1 className="text-lg font-semibold tracking-tight text-slate-800 dark:text-slate-200">
                Proximity
              </h1>
            </div>
          </div>
          <div
            style={{ "--wails-draggable": "no-drag" }}
            className="flex items-center gap-2"
          >
            {port != null && (
              <span
                className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium select-text cursor-text bg-black/10 dark:bg-black/20 shadow-inner shadow-black/10 text-slate-500 dark:text-slate-400`}
              >{`Port ${port}`}</span>
            )}
            {!running ? (
              <button
                onClick={onStart}
                className="inline-flex items-center justify-center w-28 rounded-md bg-[#0a84ff] hover:bg-[#409cff] text-white font-medium px-3 py-1.5 text-sm transition border border-white/20 shadow-lg shadow-black/20"
              >
                Start Proxy
              </button>
            ) : (
              <button
                onClick={onStop}
                className="inline-flex items-center justify-center w-28 rounded-md bg-[#ff453a] hover:bg-[#ff6961] text-white font-medium px-3 py-1.5 text-sm transition border border-white/20 shadow-lg shadow-black/20"
              >
                Stop Proxy
              </button>
            )}
          </div>
        </div>
      </header>

      <main className="flex-1 overflow-hidden min-h-0 min-w-0 p-1">
        <div className="shadow-md bg-neutral-100/60 dark:bg-neutral-900 p-0 h-full min-h-0 min-w-0 w-full flex flex-col overflow-hidden rounded-lg">
          <div
            ref={logsRef}
            className="flex-1 min-h-0 min-w-0 overflow-auto no-scrollbar"
          >
            {activeTab === "logs" ? (
              <div className="font-mono text-xs leading-relaxed text-slate-800/90 dark:text-slate-200/90 whitespace-pre-wrap break-all w-full min-w-0 min-h-0 select-text p-4">
                {logs?.length ? logs : "No logs yet."}
              </div>
            ) : (
              <div className="p-2">
                {endpoints?.length ? (
                  <div className="space-y-3">
                    {Object.entries(groupEndpoints(endpoints)).map(
                      ([provider, providerEndpoints]) => {
                        return (
                          <div
                            key={provider}
                            className="rounded-lg bg-[hsl(240,5%,15%)] shadow-lg shadow-black/20 border border-[hsl(240,5%,14%)] overflow-hidden"
                          >
                            <div
                              className="px-3 py-3.5 border-b border-[hsl(240,5%,11%)] bg-black/20 flex items-center gap-3"
                            >
                              {getProviderLogo(provider) && (
                                <img 
                                  src={getProviderLogo(provider)} 
                                  alt={`${provider} logo`}
                                  className="w-6 h-6 object-contain select-none pointer-events-none"
                                  draggable="false"
                                />
                              )}
                              <h2 className="text-lg font-semibold tracking-wide text-slate-700 dark:text-slate-200">
                                {provider}
                              </h2>
                            </div>
                            <div className="divide-y divide-[hsl(240,5%,12%)]">
                              {providerEndpoints.map((e, i) => (
                                <div
                                  key={i}
                                  className="p-3"
                                >
                                  <div className="text-[15px] font-medium text-slate-700 dark:text-slate-200">
                                    {describeEndpoint(e.in)}
                                  </div>
                                  <div className="mt-1.5">
                                    <code 
                                      onClick={() => copyToClipboard(e.in)}
                                      className="inline-block font-mono text-sm text-slate-800 dark:text-slate-100 bg-black/5 dark:bg-black/20 ring-1 ring-black/10 dark:ring-white/10 rounded px-3 py-1.5 hover:bg-black/10 dark:hover:bg-black/30 transition-colors select-none"
                                      style={{ cursor: 'pointer' }}
                                    >
                                      {e.in}
                                    </code>
                                  </div>
                                </div>
                              ))}
                            </div>
                          </div>
                        );
                      }
                    )}
                  </div>
                ) : (
                  <div className="text-sm text-slate-400 dark:text-slate-500">
                    No endpoints configured.
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Copy to clipboard toast notification */}
      <div 
        className={`fixed bottom-6 left-1/2 -translate-x-1/2 z-50 transition-all duration-300 ease-out ${
          showCopiedToast 
            ? 'translate-y-0 opacity-100' 
            : 'translate-y-8 opacity-0 pointer-events-none'
        }`}
      >
        <div className="bg-white text-slate-800 font-medium text-sm px-4 py-2 rounded-full shadow-xl shadow-black/30 border border-white/20">
          Copied to clipboard
        </div>
      </div>
    </div>
  );
}
