import React, { useEffect, useRef, useState } from "react";

// Wails runtime event helpers (already generated by template)
import { EventsOn, EventsOff } from "../wailsjs/runtime/runtime.js";

// Prefer the generated bindings if they exist, otherwise fall back to window.go
// The generated file will update after running `wails dev`/`wails build`
let API = null;
try {
  // eslint-disable-next-line no-undef
  API = window?.go?.app?.App;
} catch (_) {
  API = null;
}

function Badge({ children, variant = "success" }) {
  const color =
    variant === "success"
      ? "bg-emerald-500/15 text-emerald-300 ring-emerald-500/20"
      : variant === "danger"
      ? "bg-rose-500/15 text-rose-300 ring-rose-500/20"
      : "bg-slate-500/15 text-slate-300 ring-slate-500/20";
  return (
    <span className={`inline-flex items-center px-2 py-1 rounded-md text-xs font-medium ring-1 ring-inset ${color}`}>
      {children}
    </span>
  );
}

export default function App() {
  const [configPath, setConfigPath] = useState("");
  const [port, setPort] = useState(3001);
  const [running, setRunning] = useState(false);
  const [logs, setLogs] = useState("");
  const [busy, setBusy] = useState(false);

  // Dark theme only
  const logsRef = useRef(null);

  // Auto-scroll logs
  useEffect(() => {
    if (!logsRef.current) return;
    logsRef.current.scrollTop = logsRef.current.scrollHeight;
  }, [logs]);

  // Initialisation: fetch defaults & status
  useEffect(() => {
    let mounted = true;

    (async () => {
      try {
        // if (API?.DefaultConfigPath) {
        //   const p = await API.DefaultConfigPath();
        //   if (mounted && p) setConfigPath(p);
        // }
        if (API?.IsRunning) {
          const s = await API.IsRunning();
          if (mounted) setRunning(!!s);
        }
        if (API?.GetLogs) {
          const l = await API.GetLogs();
          if (mounted && l) setLogs(l);
        }
      } catch (e) {
        // ignore
      }
    })();

    // Subscribe to runtime events
    const offA = EventsOn("proxy:status", (status) => {
      setRunning(status === "running");
    });
    const offB = EventsOn("proxy:log", (line) => {
      setLogs((prev) => prev + (prev.endsWith("\n") || prev.length === 0 ? "" : "\n") + line);
    });
    const offC = EventsOn("proxy:log:cleared", () => setLogs(""));

    return () => {
      mounted = false;
      try {
        EventsOff("proxy:status", offA);
        EventsOff("proxy:log", offB);
        EventsOff("proxy:log:cleared", offC);
      } catch (_) {
        // ignore
      }
    };
  }, []);

  // const onBrowse = async () => {
  //   if (!API?.OpenConfigDialog) return;
  //   const p = await API.OpenConfigDialog();
  //   if (p) setConfigPath(p);
  // };

  const onStart = async () => {
    if (!API?.StartProxy) return;
    setBusy(true);
    try {
      await API.StartProxy(configPath, Number(port));
    } catch (e) {
      console.error(e);
    } finally {
      setBusy(false);
    }
  };

  const onStop = async () => {
    if (!API?.StopProxy) return;
    setBusy(true);
    try {
      await API.StopProxy();
    } catch (e) {
      console.error(e);
    } finally {
      setBusy(false);
    }
  };

  const onClearLogs = async () => {
    if (!API?.ClearLogs) {
      setLogs("");
      return;
    }
    await API.ClearLogs();
  };

  return (
    <div className="h-screen overflow-hidden select-none bg-neutral-900 text-slate-200 selection:bg-brand-300/20 relative flex flex-col">
      <div className="fixed top-0 left-0 right-0 h-2 app-drag z-10" />
      <header className="hidden">
        <div className="w-full flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-9 w-9 rounded-lg bg-brand-500/20 ring-1 ring-brand-500/30 grid place-items-center shadow-card">
              <div className="h-2.5 w-2.5 rounded bg-brand-400" />
            </div>
            <div>
              <h1 className="text-lg font-semibold tracking-tight">Central AI Proxy — Desktop</h1>
              <p className="text-xs text-slate-400">
                Beautiful, local control surface for your AI proxy
              </p>
            </div>
          </div>
          <div>
            {running ? <Badge>Running</Badge> : <Badge variant="danger">Stopped</Badge>}
          </div>
        </div>
      </header>

      <main className="p-2 flex-1 overflow-hidden min-h-0 min-w-0">
        <div className="w-full grid h-full min-h-0 min-w-0 overflow-hidden gap-2 md:grid-cols-[260px_minmax(0,1fr)]">
          {/* Control Panel */}
          <section>
            <div className="h-full min-h-0 flex flex-col">
              <h2 className="text-sm font-medium text-slate-200 mb-4">Configuration</h2>


              <div className="mt-4">
                <label className="text-xs text-slate-400">Port</label>
                <input
                  type="number"
                  min={1}
                  max={65535}
                  className="mt-1.5 w-32 rounded-lg bg-neutral-900 border border-neutral-800 px-3 py-2 text-sm text-slate-200 outline-none focus:ring-2 focus:ring-brand-500/30"
                  value={port}
                  onChange={(e) => setPort(e.target.value)}
                />
              </div>

              <div className="mt-auto flex flex-col gap-2 pt-4">
                {!running ? (
                  <button
                    disabled={busy}
                    onClick={onStart}
                    className="inline-flex w-full items-center justify-center rounded-lg bg-brand-500 hover:bg-brand-400 text-slate-900 font-medium px-4 py-2 text-sm disabled:opacity-50 disabled:cursor-not-allowed transition"
                  >
                    Start Proxy
                  </button>
                ) : (
                  <button
                    disabled={busy}
                    onClick={onStop}
                    className="inline-flex w-full items-center justify-center rounded-lg bg-rose-500 hover:bg-rose-400 text-slate-900 font-medium px-4 py-2 text-sm disabled:opacity-50 disabled:cursor-not-allowed transition"
                  >
                    Stop Proxy
                  </button>
                )}

                <button
                  onClick={onClearLogs}
                  className="inline-flex w-full items-center justify-center rounded-lg border border-white/10 bg-white/10 hover:bg-white/15 px-4 py-2 text-sm transition"
                >
                  Clear logs
                </button>
              </div>

            </div>
          </section>

          {/* Logs */}
          <section className="md:col-start-2 min-h-0 min-w-0 h-full overflow-hidden">
            <div className="rounded-md border border-neutral-700 bg-neutral-800/60 backdrop-blur p-1 shadow-card h-full min-h-0 min-w-0 w-full flex flex-col overflow-hidden">
              <div className="flex items-center justify-between mb-2 p-2 rounded-md bg-neutral-800/50 border border-neutral-700 shrink-0">
                <div className="text-xs font-medium text-slate-200">Logs</div>
                {running ? <Badge>Running</Badge> : <Badge variant="danger">Idle</Badge>}
              </div>
              <div
                ref={logsRef}
                className="font-mono text-xs leading-relaxed text-slate-200/90 whitespace-pre-wrap break-all bg-neutral-900 rounded-md border border-neutral-700 p-2 overflow-auto flex-1 w-full min-w-0 min-h-0 max-h-full select-text"
              >
                {logs?.length ? logs : "No logs yet."}
              </div>
            </div>
          </section>
        </div>
      </main>

    </div>
  );
}
